/*
    Exercise 5
    Directory: w45/e05
    Objective:
        - Create a 2D array representing a matrix and write a program to transpose it (swap rows and columns).
    Expected Output:
        - Print the original and transposed matrix. 
        - Use Math.random() to generate the values
*/

import java.util.Random;

public class App {
    final static int ROWS = 9;
    final static int COLUMNS = 9;

    public static void main(String[] args) {
        Random rnd = new Random();

        // YOUR CODE GOES HERE
        int[][] originalMatrix = new int[ROWS][COLUMNS];

        for (int i = 0; i < originalMatrix.length; i++) {
            for (int j = 0; j < originalMatrix[i].length; j++) {
                originalMatrix[i][j] = rnd.nextInt(20);
            }
        }


        int[][] transposedMatrix = new int[ROWS][COLUMNS];

        // Generated by ChatGPT :)
        for (int i = 0; i < originalMatrix.length; i++) {
            for (int j = 0; j < originalMatrix[i].length; j++) {
                transposedMatrix[j][i] = originalMatrix[i][j];
            }
        }

        System.out.println("Original:");
        for (int i = 0; i < originalMatrix.length; i++) {
            for (int y = 0; y < originalMatrix[i].length; y++) {
                System.out.print(originalMatrix[i][y] + " ");
            }
            System.out.println("");
        }

        System.out.println("Transposed:");
        for (int i = 0; i < transposedMatrix.length; i++) {
            for (int y = 0; y < transposedMatrix[i].length; y++) {
                System.out.print(transposedMatrix[i][y] + " ");
            }
            System.out.println("");
        }
    }
}